theme: jekyll-theme-minimal
title: "Henning<br>Agt-Rickauer"
description: "Personal page"
navigation:
  - title: "Short CV"
    url: /cv/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
