theme: jekyll-theme-minimal
title: "Henning Agt-Rickauer"
description: "Personal page of Henning Agt-Rickauer"
navigation:
  - title: "Home"
    url: /    
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
