theme: jekyll-theme-minimal
title: "Henning<br>Agt-Rickauer"
description: "Personal page of Henning Agt-Rickauer"
navigation:
  - title: "Home"
    url: /    
  - title: "Short CV"
    url: /cv/
  - title: "Projects"
    url: /projects/
  - title: "Publications"
    url: /publications/
